FROM golang:1.24-alpine

ENV GO111MODULE=on \
    CGO_ENABLED=1

WORKDIR /app

# Install build and runtime dependencies
RUN apk add --no-cache gcc musl-dev git ca-certificates tzdata

# Install Air for live reload
RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8000

CMD ["air"]
